name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Gradle
      run: ./gradlew build

    - name: Distribute App for master
      if: github.ref == 'master'
      run: |
        curl \
         -F "token=${{secrets.DEPLOYGATE_TOKEN}}" \
         -F "file=@app/build/outputs/apk/debug/app-debug.apk" \
         -F "message=https://github.com/jiikko/first_android_app/commit/`git rev-parse --short $GITHUB_SHA`" \
         -F "distribution_name='first application(master)'" \
         https://deploygate.com/api/users/jiikko/apps
    - name: Distribute App
      if: github.ref != 'master'
      run: |
        curl \
         -F "token=${{secrets.DEPLOYGATE_TOKEN}}" \
         -F "file=@app/build/outputs/apk/debug/app-debug.apk" \
         -F "message=https://github.com/jiikko/first_android_app/commit/`git rev-parse --short $GITHUB_SHA`" \
         -F "distribution_name=first application(#`echo $GITHUB_EVENT_PATH | jq -r`".number")" \
         https://deploygate.com/api/users/jiikko/apps
